# Generated by Django 5.0.2 on 2024-03-18 16:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('USER', 'User'), ('VENDOR', 'Vendor')], max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [],
            },
            managers=[
                ('user', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AllergenModel',
            fields=[
                ('allergen_id', models.AutoField(primary_key=True, serialize=False)),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('milk', models.BooleanField(default=False)),
                ('eggs', models.BooleanField(default=False)),
                ('fish', models.BooleanField(default=False)),
                ('crustacean', models.BooleanField(default=False)),
                ('tree_nuts', models.BooleanField(default=False)),
                ('peanuts', models.BooleanField(default=False)),
                ('wheat', models.BooleanField(default=False)),
                ('soybeans', models.BooleanField(default=False)),
                ('sesame', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='QuizRecordModel',
            fields=[
                ('quiz_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('permission_level', models.IntegerField(default=0)),
            ],
            options={
                'permissions': [],
            },
            bases=('user_api.usermodel',),
            managers=[
                ('admin', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BagGroupModel',
            fields=[
                ('bag_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('bags_unclaimed', models.IntegerField(default=0)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.allergenmodel')),
            ],
        ),
        migrations.CreateModel(
            name='BagModel',
            fields=[
                ('bag_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_time', models.DateTimeField()),
                ('claimed', models.BooleanField(default=False)),
                ('bag_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.baggroupmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimModel',
            fields=[
                ('claim_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('success', models.BooleanField(default=False)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.bagmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=128)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.questionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VendorModel',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bags_left', models.IntegerField(default=0)),
                ('icon', models.CharField(default='https://pbs.twimg.com/profile_images/1657489733/ram2_400x400.jpg', max_length=256)),
                ('banner', models.CharField(default='https://liveevents.exeter.ac.uk/wp-content/uploads/2022/02/Section-1.png', max_length=256)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.locationmodel')),
            ],
            options={
                'permissions': [],
            },
            bases=('user_api.usermodel',),
            managers=[
                ('vendor', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='your_default_value', max_length=128)),
                ('image_url', models.CharField(default='your_default_value', max_length=128)),
                ('vendor_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_api.vendormodel')),
            ],
        ),
        migrations.AddField(
            model_name='baggroupmodel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.vendormodel'),
        ),
    ]
