# Generated by Django 4.1 on 2024-02-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_rename_time_bagmodel_collection_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormodel',
            name='bags_left',
            field=models.IntegerField(default=0),
        ),
    ]
