# Generated by Django 5.1.dev20240122042528 on 2024-02-26 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0004_alter_questionmodel_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claimmodel",
            name="success",
        ),
    ]
