# Generated by Django 5.0.1 on 2024-02-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_websiteusermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bagmodel',
            old_name='time',
            new_name='collection_time',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_vendor',
        ),
        migrations.RemoveField(
            model_name='vendormodel',
            name='num_bags',
        ),
        migrations.AddField(
            model_name='appuser',
            name='vendor_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vendormodel',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
